export const SET_POST = 'POST/SET_POST';
export const REQUEST_POST_START = 'POST/REQUEST_FEED_START';

export const REQUEST_POST_SUCCESS = 'POST/REQUEST_FEED_SUCCESS';
export const REQUEST_POST_FAILURE = 'POST/REQUEST_FEED_FAILURE';

export const POST_COMMENT = 'POST/POST_COMMENT';
export const DELETE_COMMENT = 'POST/DELETE_COMMENT';
export const ADD_LIKE_POST = 'POST/ADD_LIKE_POST';
export const DELETE_LIKE_POST = 'POST/DELETE_LIKE_POST';
