export const SET_POST = 'POST/SET_POST';
export const REQUEST_POST_START = 'POST/REQUEST_FEED_START';

export const REQUEST_POST_SUCCESS = 'POST/REQUEST_FEED_SUCCESS';
export const REQUEST_POST_FAILURE = 'POST/REQUEST_FEED_FAILURE';

export const ADD_LIKE_POST = 'POST/ADD_LIKE_POST';
export const DELETE_LIKE_POST = 'POST/DELETE_LIKE_POST';
export const ADD_ONE_COUNTER_COMMENT = 'POST/ADD_ONE_COUNTER_COMMENT';
export const REMOVE_ONE_COUNTER_COMMENT = 'POST/REMOVE_ONE_COUNTER_COMMENT';

export const UNFOLLOW_USER_POST = 'POST/UNFOLLOW_USER_POST';

export const FOLLOW_USER_POST = 'POST/FOLLOW_USER_POST';
