export const SET_COMMENTS = 'COMMENT/SET_COMMENTS';

export const SET_COMMENTS_CURSOR = 'COMMENT/SET_COMMENTS_CURSOR';

export const LOAD_MORE_COMMENT = 'COMMENT/LOAD_MORE_COMMENT';

export const SET_MORE_PAGE_COMMENT = 'COMMENT/SET_MORE_PAGE_COMMENT';
