export const SET_COMMENTS = 'COMMENT/SET_COMMENTS';

export const SET_COMMENTS_CURSOR = 'COMMENT/SET_COMMENTS_CURSOR';

export const LOAD_MORE_COMMENT = 'COMMENT/LOAD_MORE_COMMENT';

export const SET_MORE_PAGE_COMMENT = 'COMMENT/SET_MORE_PAGE_COMMENT';

export const POST_NEW_COMMENT = 'COMMENT/POST_NEW_COMMENT';

export const DELETE_ONE_COMMENT = 'COMMENT/DELETE_ONE_COMMENT';
