export const SET_FEED = 'FEED/SET_USER_FEED';

export const REQUEST_FEED_START = 'FEED/REQUEST_FEED_START';

export const REQUEST_FEED_SUCCESS = 'FEED/REQUEST_FEED_SUCCESS';
export const REQUEST_FEED_FAILURE = 'FEED/REQUEST_FEED_FAILURE';
